import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export default function Model(props) {
	const group = useRef()
	const { nodes, materials } = useGLTF("/AMG.gltf")

	return (
		<group ref={group} {...props} dispose={null}>
			<group
				position={[1.56, 0.35, 0]}
				rotation={[0, 0, -Math.PI / 2]}
				scale={[0.03, 0.03, 0.03]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Bolt001.geometry}
					material={nodes.Bolt001.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Bolt001_1.geometry}
					material={nodes.Bolt001_1.material}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円014.geometry}
				material={materials["マテリアル.293"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円014_1.geometry}
				material={nodes.円014_1.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円014_2.geometry}
				material={materials["マテリアル.288"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円014_3.geometry}
				material={nodes.円014_3.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円014_4.geometry}
				material={nodes.円014_4.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円014_5.geometry}
				material={materials["マテリアル.033"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002.geometry}
				material={materials["マテリアル.286"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_1.geometry}
				material={materials["マテリアル.002"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_2.geometry}
				material={materials["マテリアル.287"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_3.geometry}
				material={materials["マテリアル.259"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_4.geometry}
				material={materials["マテリアル.019"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_5.geometry}
				material={materials["マテリアル.020"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_6.geometry}
				material={materials["マテリアル.018"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_7.geometry}
				material={materials["マテリアル.017"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_8.geometry}
				material={materials["マテリアル.254"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_9.geometry}
				material={materials["マテリアル.253"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_10.geometry}
				material={materials["マテリアル.258"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_11.geometry}
				material={materials["マテリアル.257"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_12.geometry}
				material={materials["マテリアル.256"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_13.geometry}
				material={materials["マテリアル.255"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円002_14.geometry}
				material={materials["マテリアル.021"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円003.geometry}
				material={nodes.円003.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円003_1.geometry}
				material={nodes.円003_1.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円003_2.geometry}
				material={nodes.円003_2.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円003_3.geometry}
				material={nodes.円003_3.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円012.geometry}
				material={nodes.円012.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円012_1.geometry}
				material={nodes.円012_1.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円012_2.geometry}
				material={nodes.円012_2.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円012_3.geometry}
				material={nodes.円012_3.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.wheel_RR.geometry}
				material={nodes.wheel_RR.material}
				position={[0.69, 0.27, -0.76]}
				rotation={[-3.14, -Math.PI / 2, 0]}
				scale={[0.11, 0.11, 0.11]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.wheel_RF.geometry}
				material={nodes.wheel_RF.material}
				position={[-1.38, 0.25, -0.75]}
				rotation={[-3.14, -Math.PI / 2, 0]}
				scale={[0.11, 0.11, 0.11]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.light_R.geometry}
				material={materials["マテリアル.243"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.wheel_LR.geometry}
				material={nodes.wheel_LR.material}
				position={[0.69, 0.26, 0.76]}
				rotation={[0, -Math.PI / 2, 0]}
				scale={[0.11, 0.11, 0.11]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.spoiler.geometry}
				material={materials["マテリアル.242"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面099.geometry}
				material={materials["マテリアル.201"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面099_1.geometry}
				material={materials["マテリアル.192"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.LED_red.geometry}
				material={materials["マテリアル.007"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.tyreLF.geometry}
				material={nodes.tyreLF.material}
				position={[-0.34, 0.1, -0.01]}
				rotation={[Math.PI / 2, 0, Math.PI / 2]}
				scale={[0.78, 0.78, 0.78]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.tyreLR.geometry}
				material={nodes.tyreLR.material}
				position={[-0.34, 0.1, 0.01]}
				rotation={[Math.PI / 2, 0, Math.PI / 2]}
				scale={[0.78, 0.78, 0.78]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.tyreRR.geometry}
				material={nodes.tyreRR.material}
				position={[-0.34, 0.1, -0.02]}
				rotation={[Math.PI / 2, 0, Math.PI / 2]}
				scale={[0.78, 0.78, 0.78]}
			/>
			<group
				position={[-1.4, 0.19, 0.38]}
				rotation={[1.07, 0.62, -2.19]}
				scale={[0.8, 0.61, 0.8]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面005.geometry}
					material={materials["マテリアル.260"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面005_1.geometry}
					material={materials["マテリアル.238"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面005_2.geometry}
					material={materials["マテリアル.221"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面005_3.geometry}
					material={materials["マテリアル.220"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面005_4.geometry}
					material={materials["マテリアル.005"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面005_5.geometry}
					material={materials.マテリアル}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面005_6.geometry}
					material={materials["マテリアル.014"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面005_7.geometry}
					material={materials["マテリアル.013"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面005_8.geometry}
					material={materials["マテリアル.015"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面005_9.geometry}
					material={materials["マテリアル.011"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面042.geometry}
				material={materials["マテリアル.248"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面042_1.geometry}
				material={materials["マテリアル.247"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面042_2.geometry}
				material={materials["マテリアル.246"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面042_3.geometry}
				material={materials["マテリアル.191"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面042_4.geometry}
				material={materials["マテリアル.016"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面044.geometry}
				material={nodes.平面044.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面044_1.geometry}
				material={materials["マテリアル.212"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面044_2.geometry}
				material={nodes.平面044_2.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面044_3.geometry}
				material={materials["マテリアル.051"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面044_4.geometry}
				material={materials["マテリアル.244"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面044_5.geometry}
				material={materials["マテリアル.203"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面026.geometry}
				material={materials["マテリアル.236"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面026_1.geometry}
				material={materials["マテリアル.039"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面026_2.geometry}
				material={materials["マテリアル.040"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面026_3.geometry}
				material={materials["マテリアル.237"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面026_4.geometry}
				material={materials["マテリアル.233"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面026_5.geometry}
				material={materials["マテリアル.232"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面019.geometry}
				material={materials["マテリアル.213"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面019_1.geometry}
				material={materials["マテリアル.265"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面019_2.geometry}
				material={materials["マテリアル.274"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面019_3.geometry}
				material={materials["マテリアル.275"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面107.geometry}
				material={materials["マテリアル.190"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面107_1.geometry}
				material={materials["マテリアル.189"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面107_2.geometry}
				material={materials["マテリアル.188"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.wheel_LF.geometry}
				material={nodes.wheel_LF.material}
				position={[-1.38, 0.25, 0.75]}
				rotation={[0, -Math.PI / 2, 0]}
				scale={[0.11, 0.11, 0.11]}
			/>
			<group
				position={[-2.19, 0.22, 0]}
				rotation={[Math.PI, 0, Math.PI / 2]}
				scale={[0.03, 0.03, 0.03]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Bolt002.geometry}
					material={nodes.Bolt002.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Bolt002_1.geometry}
					material={nodes.Bolt002_1.material}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mirror_clear.geometry}
				material={materials["マテリアル.022"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.mirror_LED.geometry}
				material={materials["マテリアル.023"]}
			/>
			<group
				position={[1.34, 0.64, 0.35]}
				rotation={[-3.13, 0.11, 2.42]}
				scale={[0.02, 0.02, 0.02]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面145.geometry}
					material={nodes.平面145.material}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面145_1.geometry}
					material={materials["マテリアル.004"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.平面145_2.geometry}
					material={materials["マテリアル.003"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.tyreRF.geometry}
				material={nodes.tyreRF.material}
				position={[-0.34, 0.1, -0.02]}
				rotation={[Math.PI / 2, 0, Math.PI / 2]}
				scale={[0.78, 0.78, 0.78]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面024.geometry}
				material={materials["マテリアル.010"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面024_1.geometry}
				material={materials["マテリアル.012"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円柱.geometry}
				material={materials["マテリアル.045"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円柱_1.geometry}
				material={materials["マテリアル.025"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円柱_2.geometry}
				material={materials["マテリアル.047"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円柱_3.geometry}
				material={materials["マテリアル.046"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円柱_4.geometry}
				material={materials["マテリアル.048"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円柱_5.geometry}
				material={materials["マテリアル.049"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円柱_6.geometry}
				material={materials["マテリアル.038"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円柱_7.geometry}
				material={materials["マテリアル.042"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円柱_8.geometry}
				material={materials["マテリアル.043"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円柱_9.geometry}
				material={materials["マテリアル.044"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.円柱_10.geometry}
				material={materials["マテリアル.041"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面093.geometry}
				material={materials["マテリアル.200"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面093_1.geometry}
				material={materials["マテリアル.199"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面093_2.geometry}
				material={materials["マテリアル.194"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面133.geometry}
				material={materials["マテリアル.029"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面133_1.geometry}
				material={materials["マテリアル.300"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面133_2.geometry}
				material={materials["マテリアル.030"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面133_3.geometry}
				material={materials["マテリアル.024"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面133_4.geometry}
				material={materials["マテリアル.027"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.平面133_5.geometry}
				material={materials["マテリアル.031"]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.brake_F.geometry}
				material={nodes.brake_F.material}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.brake_R.geometry}
				material={nodes.brake_R.material}
			/>
		</group>
	)
}

useGLTF.preload("/AMG.gltf")
